/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "driver/pwm.h"
#include "driver/encoder.h"
#include "driver/stm.h"
#include "driver/user_MotorCtl.h"
#include "driver/asclin.h"
#include "driver/can.h"
#include "driver/main.h"
#include "driver/uss.h"


IfxCpu_syncEvent g_cpuSyncEvent = 0;

// CAN 관련
/* 글로벌 핸들 */
IfxMultican_Can        g_can;         // CAN 모듈 핸들
IfxMultican_Can_Node   g_canNode;     // CAN 노드 핸들
IfxMultican_Can_MsgObj g_txMsgObj;    // 송신 메시지 오브젝트
IfxMultican_Can_MsgObj g_rxMsgObj;    // 수신 메시지 오브젝트
/* 송신 메시지 */
IfxMultican_Message g_txMsg;
/* 수신 메시지 */
IfxMultican_Message g_rxMsg;
// CAN bus 상태
IfxMultican_Status g_status;


Motor_t g_motor;    // 모터 제어 글로벌 변수


volatile uint32 avg_speed;
void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
        

    initShellInterface();
    initCan();
    Driver_Stm_Init();      // 스케줄링
    initEncoder();          // 엔코더 초기화
    ultrasonic_init();      // 초음파 센서 초기화

    initPwm();              // PWM 초기화
    startPwm();             // PWM 시작


    IfxPort_setPinModeOutput(Motor_DIR_PIN, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(Motor_DIR_PIN);

    print("hi, I'm MCU\n\r");

    // Test
    // g_motor.pwm = 3600;
    // g_motor.dir = GO_FRONT; // 전진 방향

    while(1)
    {
        AppScheduling();
    }
}




void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;

    /*------------------- 속도 측정 -----------------------*/
    getSpeed(10);  // 속도 측정
    g_motor.speed = (sint16)((measured_speed.lspeed - measured_speed.rspeed) / 2 + measured_speed.rspeed); // 평균 속도


    /*------------------- 모터 제어 -----------------------*/
    setPwm(REAR, g_motor.pwm);      // 모터 duty 설정

    if(g_motor.dir == GO_FRONT) {   // 방향 설정
        IfxPort_setPinLow(Motor_DIR_PIN);
    } else if(g_motor.dir == GO_BACK) {
        IfxPort_setPinHigh(Motor_DIR_PIN);
    } else {
        print("Unknown direction: %d\n\r", g_motor.dir);
    }



    /*------------------- can 전송 -----------------------*/
    // can 전송 : 모터 pwm, 방향
    /*
    총 6byte 전송
    2byte : 왼쪽 pwm
    1bit : 왼쪽 방향
    2byte : 오른쪽 pwm
    1bit : 오른쪽 방향
    */

    if(stTestCnt.u32nuCnt10ms % 5 != 0) {
        g_txMsg.id = 0x204;
        g_txMsg.lengthCode = 4;

        g_txMsg.data[0] = (uint32)((uint32)g_motor.pwm << 16 | (uint32)(g_motor.speed * 5));
        g_txMsg.data[1] = (uint32)(0x00);
        g_status = sendCanMessage();  // 메시지 전송

        // can 오류 : 정지
        if(g_status == 32) {
            g_motor.dir = GO_FRONT;
            g_motor.pwm = 0;
        }
    }



    // g_txMsg.id = 0x204;
    // g_txMsg.lengthCode = 4;

    // g_txMsg.data[0] = (uint32)((uint32)g_motor.pwm << 16 | (uint32)(g_motor.speed * 5));
    // g_txMsg.data[1] = (uint32)(0x00);
    // g_status = sendCanMessage();  // 메시지 전송
    
    static int i=0;
    if(i++ % 100 == 0) {
        print("\r\n--------------------------\r\n");
        print("pwm : %d, dir : %d, speed : %d\n\r", g_motor.pwm, g_motor.dir, g_motor.speed);
        print("lspeed : %.3lf, rspeed : %.3lf\n\r", measured_speed.lspeed, measured_speed.rspeed);
        print("can send status : %d\n\r", g_status);
    }


    /*------------------- 초음파 거리 측정 -----------------------*/
    if(stTestCnt.u32nuCnt10ms % 5 == 0) { // 50ms 주기로 초음파 거리 측정
        int distance = measure_ultrasonic_distance();

        g_txMsg.id = 0x112;
        g_txMsg.lengthCode = 2;
        g_txMsg.data[0] = (uint32)((uint8)distance << 8 | (uint8)distance);
        g_txMsg.data[1] = (uint32)(0x00);
        g_status = sendCanMessage();  // 메시지 전송

        static int i = 0;
        if(i++ % 20 == 0) {
            print("Distance: %d cm | can status : %d\n\r", distance, g_status);
        }

    }


}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
}

void AppTask1000ms(void)
{
    stTestCnt.u32nuCnt1000ms++;
}
