/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "driver/Flash_Programming.h"
#include "driver/can.h"
#include "driver/start.h"
#include "driver/asclin.h"
#include "driver/main.h"
#include "driver/stm.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;


// CAN 관련
/* 글로벌 핸들 */
IfxMultican_Can        g_can;         // CAN 모듈 핸들
IfxMultican_Can_Node   g_canNode;     // CAN 노드 핸들
IfxMultican_Can_MsgObj g_txMsgObj;    // 송신 메시지 오브젝트
//IfxMultican_Can_MsgObj g_rxMsgObj;    // 수신 메시지 오브젝트
/* 송신 메시지 */
IfxMultican_Message g_txMsg;
/* 수신 메시지 */
IfxMultican_Message g_rxMsg;
// CAN bus 상태
IfxMultican_Status g_status;


Core_Mode_t core_mode;  // 현재 코어 모드

Hbeam_t g_hbeam;        // 하이빔 상태




void wait_ms(uint32 ms)
{
    uint32 start = IfxStm_getLower(&MODULE_STM0);  // 현재 시간
    uint32 delayTicks = IfxStm_getTicksFromMilliseconds(&MODULE_STM0, ms);  // 100ms → 틱 변환

    // unsigned 비교: 오버플로 대비
    while ((IfxStm_getLower(&MODULE_STM0) - start) < delayTicks)
    {
        __nop();  // CPU가 너무 바빠지지 않게 NOP 삽입 (선택)
    }
}




 void welcomeLED0() __attribute__((section(".otaSection0")))       // 현재 사용 섹션
 {
    int num = 2;
    while(num--) {
        allset();
        for(volatile int i=0;i<4000000;i++);
        allclear();
        for(volatile int i=0;i<4000000;i++);
    }
    ;
 }
 void welcomeLED1() __attribute__((section(".otaSection1")))       // 현재 사용 섹션
 {
    int num = 2;
    while(num--) {
        allset();
        for(volatile int i=0;i<4000000;i++);
        allclear();
        for(volatile int i=0;i<4000000;i++);
    }
    ;
 }

void core0_main(void)
{
    //  software_init_hook();

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    

    IfxPort_setPinModeOutput(LEDL, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LEDR, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);


    initShellInterface();
    initCan();
    Driver_Stm_Init();

    print("hi, cur Addr :  0x%X\n\r", (uint32)g_funcptr.ota);



    g_funcptr.ota();    // 웰컴 라이트


    while(1)
    {
        if(core_mode == OPERATING) {

            /*----------- 하이빔 상태 전송 canid 0x154, 100ms -------------*/
            wait_ms(100);  // 100ms 대기
            
            static int temp = 0;
            if (temp++ % 10 == 0) {
                led8Ctl();  // 상향등 상태에 따라 LED 제어
            }

            //led8Ctl();  // 상향등 상태에 따라 LED 제어

            g_txMsg.id = 0x154;
            g_txMsg.lengthCode = 3; // 낮은거 부터 3바이트네
            //g_hbeam.onoff = 1;
            // g_hbeam.posl = 0x00;  // 우측 LED 상태
            //g_hbeam.posr = 0xFE;  // 좌측 LED 상태
            g_txMsg.data[0] = (uint32)((uint32)g_hbeam.onoff << 0 | (uint32)g_hbeam.posl << 8 | (uint32)g_hbeam.posr << 16);   // lsb에 맞춰서 보냄
            g_txMsg.data[1] = (uint32)(0x00);
            g_status = sendCanMessage();  // 메시지 전송

            static int i=0;
            if (i++ % 10 == 0) {
                ;
                //led8Ctl();  // 상향등 상태에 따라 LED 제어
                //print("\n\r----------------Operating Mode-----------------n\r");
                print("onoff : %d | left  : %X | right : %X\n\r", g_hbeam.onoff, g_hbeam.posl, g_hbeam.posr);
                print("can status : %d\n\r", g_status);

                print("\n\r");
            }


            /*---------------------ota용---------------------------*/
            //g_funcptr.ota();
            //func();   // 내 함수
        }
        else if(core_mode == UPDATING) {
            if(ota_write_flag == 1) {
                ota_write_flag = 0;
                print("======Write START======\n\r");
                for(volatile int i=0;i<10000000;i++); // wait
                writeProgramFlash();
                core_mode = OPERATING;
                print("======Write Finish======\n\r");

            }

        }
    }
}
