/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "driver/Flash_Programming.h"
#include "driver/can.h"
#include "driver/start.h"
#include "driver/asclin.h"
#include "driver/main.h"
#include "driver/stm.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define LED1                        &MODULE_P10,5               //LED connected to Port 00, Pin 5
#define LED2                        &MODULE_P10,6               //LED connected to Port 00, Pin 6




//FuncPtr g_funcptr;  // 두 섹션 주소 저장
//int g_select __attribute__((section(".otaDataSection")));       // 현재 사용 섹션

// CAN 관련
/* 글로벌 핸들 */
IfxMultican_Can        g_can;         // CAN 모듈 핸들
IfxMultican_Can_Node   g_canNode;     // CAN 노드 핸들
IfxMultican_Can_MsgObj g_txMsgObj;    // 송신 메시지 오브젝트
IfxMultican_Can_MsgObj g_rxMsgObj;    // 수신 메시지 오브젝트
/* 송신 메시지 */
IfxMultican_Message g_txMsg;
/* 수신 메시지 */
IfxMultican_Message g_rxMsg;
// CAN bus 상태
IfxMultican_Status g_status;


Core_Mode_t core_mode;


// typedef void (*func_t)(void);
ffunc_t fff = (ffunc_t)0x80100000; // = (func_t)0x801000BC;






// void ws2812_send_byte(Ifx_P *port, uint8 pinIndex, uint8 data) __attribute__((section(".otaSection0")))
// {
//     for (int i = 7; i >= 0; i--) {
//         if (data & (1 << i)) {
//             // 1비트 전송: High 0.8us + Low 0.45us
//             IfxPort_setPinHigh(port, pinIndex);
//             waitns(70);
//             IfxPort_setPinLow(port, pinIndex);
        
//             waitns(12);
//         } else {
//             // 0비트 전송: High 0.4us + Low 0.85us
//             IfxPort_setPinHigh(port, pinIndex);
//             waitns(12);
//             IfxPort_setPinLow(port, pinIndex);
//             waitns(70);
//         }
//     }
//     // 18 : 500
//     // 80 : 1us
// }

// void ws2812_send_color(Ifx_P *port, uint8 pinIndex, uint8 g, uint8 r, uint8 b) __attribute__((section(".otaSection0")))
// {
//     IfxPort_setPinLow(port, pinIndex);
//     //waitns(3000);
//     //waitns(4500);
//     waitns(4300);
//     //waitns(1000);

//     ws2812_send_byte(port, pinIndex, g);
//     ws2812_send_byte(port, pinIndex, r);
//     ws2812_send_byte(port, pinIndex, b);

    
// }


// void func() __attribute__((section(".myfunc")))       // 현재 사용 섹션
// {
//     volatile int i = 0;
//     volatile int j = 0;
//     // IfxPort_setPinModeOutput(LEDR, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
//     // IfxPort_setPinModeOutput(LEDL, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
//     IfxPort_setPinLow(LEDL);
//     IfxPort_setPinLow(LEDR);
//     waitns(4500);

//     for(i = 0; i < 8;i++){
//         ws2812_send_color(LEDR, 0x00, 0x00, 0x00);
//     }
//     for(i = 0; i < 8;i++){
//         ws2812_send_color(LEDL, 0x00, 0x00, 0x00);
//     }

//     int num = 2;
//     while(num--) {
//         for (i = 0; i < 8; i++)
//         {
//             for (j = 0; j < 8; j++) // 한 세트 8개
//             {
//                 if (i <= j) {
//                     ws2812_send_color(LEDR, 0x00, 0x00, 0x00);  // off
//                 }
//                 else {
//                     ws2812_send_color(LEDR, 0x40, 0x40, 0x40);  // on
//                 }
//             }

//             for (j = 0; j < 8; j++) // 한 세트 8개
//             {
//                 if (i <= j) {
//                     ws2812_send_color(LEDL, 0x00, 0x00, 0x00);  // off
//                 }
//                 else {
//                     ws2812_send_color(LEDL, 0x40, 0x40, 0x40);  // on
//                 }
//             }
//             for(volatile int t=0;t<1500000;t++);
//         }

//         for (i = 0; i < 8; i++)
//         {
//             for (j = 0; j < 8; j++) // 한 세트 8개
//             {
//                 if (i >= j) {
//                     ws2812_send_color(LEDR, 0x00, 0x00, 0x00);  // off
//                 }
//                 else {
//                     ws2812_send_color(LEDR, 0x40, 0x40, 0x40);  // on
//                 }
//             }

//             for (j = 0; j < 8; j++) // 한 세트 8개
//             {
//                 if (i >= j) {
//                     ws2812_send_color(LEDL, 0x00, 0x00, 0x00);  // off
//                 }
//                 else {
//                     ws2812_send_color(LEDL, 0x40, 0x40, 0x40);  // on
//                 }
//             }
//             for(volatile int t=0;t<1500000;t++);
//         }
//     }
// }



void welcomeLED0() __attribute__((section(".otaSection0")))       // 현재 사용 섹션
{
   int num = 2;
   while(num--) {
       allset();
       for(volatile int i=0;i<4000000;i++);
       allclear();
       for(volatile int i=0;i<4000000;i++);
   }
   ;
}
void welcomeLED1() __attribute__((section(".otaSection1")))       // 현재 사용 섹션
{
   int num = 2;
   while(num--) {
       allset();
       for(volatile int i=0;i<4000000;i++);
       allclear();
       for(volatile int i=0;i<4000000;i++);
   }
   ;
}

void core0_main(void)
{
    //  software_init_hook();

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    IfxPort_setPinModeOutput(LED1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LED2, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LEDL, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LEDR, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);


    initShellInterface();
    initCan();
    Driver_Stm_Init();

    print("hi, cur Addr :  0x%X\n\r", (uint32)g_funcptr.ota);



    g_funcptr.ota();


    while(1)
    {
        if(core_mode == OPERATING) {
            //g_funcptr.ota();
            //func();   // 내 함수
        }
        else if(core_mode == UPDATING) {
            ;
        }
    }
}
